const Map<String, String> enUS = {
  'App Name': 'App Name',
  'Next': 'Next',
  'Back': 'Back',
  'Skip': 'Skip',
  'Sign In': 'Sign In',
  'Sign Up': 'Sign Up',
  'Sign Out': 'Sign Out',
  'Continue with': 'Continue with',
  'Google': 'Google',
  'Already have an account?': 'Already have an account?',
  'First name': 'First name',
  'Last name': 'Last name',
  'Username': 'Username',
  'Email': 'Email',
  'Password': 'Password',
  'Confirm password': 'Confirm password',
};
