// cSpell:disable

const Map<String, String> enUS = {
  'Dakke': 'Dakke',
  'Donya Ketab Hamrah': 'Donya Ketab Hamrah',
  'version 1.0.0': 'version 1.0.0',
  'Next': 'Next',
  'Back': 'Back',
  'Skip': 'Skip',
  'Sign In': 'Sign In',
  'Sign Out': 'Sign Out',
  'Password': 'Password',
  'Confirm password': 'Confirm password',
  'Save': 'Save',
  'Edit': 'Edit',
  'Cancel': 'Cancel',
  'Ok': 'Ok',
  'Are you sure you want to sign out?': 'Are you sure you want to sign out?',
  'I have a voucher': 'I have a voucher',
  'Phone Number': 'Phone Number',
  'ex.: 9123456789': 'ex.: 9123456789',
  'Login with password': 'Login with password',
  'Login with phone': 'Login with phone',
  'Enter the code sent to the number': 'Enter the code sent to the number',
  'Start': 'Start',
  'Is this the correct phone number?': 'Is this the correct phone number?',
  'No': 'No',
  'Yes': 'Yes',
  'Successful': 'Successful',
  'Failed': 'Failed',
  'Warning': 'Warning',
  'Payment was successful': 'Payment was successful',
  'This Part is on Develepment': 'This Part is on Develepment',
  'You have already purchased this book':
      'You have already purchased this book',
  'Try Again': 'Try Again',

  'My Books': 'My Books',
  'Recommended': 'Recommended',
  'Specials': 'Specials',
  'More': 'More',
  'Authors': 'Authors',
  'My Bookmarks': 'My Bookmarks',

  'Theme': 'Theme',
  'Dark': 'Dark',
  'Light': 'Light',
  'Device Default': 'Device Default',
  'Language': 'Language',
  'Animation': 'Animation',
  'Account Info': 'Account Info',
  'Edit Password': 'Edit Password',
  'Add to Cart': 'Add to Cart',
  'Toman': 'Toman',
  'Pay': 'Pay',
  'Payable': 'Payable',
  'Total': 'Total',
  'Discount': 'Discount',

  'Home': 'Home',
  'Search': 'Search',
  'Library': 'Library',
  'Cart': 'Cart',
  'Setting': 'Setting',
  'Detail Book': 'Detail Book',

  'Free Payment': 'Free Payment',
  'Online Reading': 'Online Reading',
  'Hear Free Audio Book': 'Hear Free Audio Book',
  'This is tha sample description text. ':
      'This is tha sample description text. ',

  //Errors
  'Password is required.': 'Password is required.',
  'Password must contain at least 8 characters.':
      'Password must contain at least 8 characters.',
  'Password must contain a-z, A-Z, 0-9.':
      'Password must contain a-z, A-Z, 0-9.',
  'Confirm Password isn\'t match.': 'Confirm Password isn\'t match.',
  'Phone number is invalid.': 'Phone number is invalid.',
  'phone or password is incorrect.': 'phone or password is incorrect.',
  'Server error. Please try again later.':
      'Server error. Please try again later.',
  'OTP code is invalid.': 'OTP code is invalid.',
  'This book is already in your cart.': 'This book is already in your cart.',
  'The cart is empty': 'The cart is empty',
  'You have not bookmarked a book yet.': 'You have not bookmarked a book yet.',
  'You have not purchased a book yet.': 'You have not purchased a book yet.',
  'Voucher Code is invalid.': 'Voucher Code is invalid.',
  'Voucher Code is applied.': 'Voucher Code is applied.',
  'Search screen is on development.': 'Search screen is on development.',
  'Connection failed': 'Connection failed',
  'No Internet Connection': 'No Internet Connection',
  'Please check your internet connection and try again.':
      'Please check your internet connection and try again.',
};
