const Map<String, String> faIR = {
  'App Name': 'اسم برنامه',
  'Next': 'بعدی',
  'Back': 'قبلی',
  'Skip': 'رد کردن',
  'Sign In': 'ورود',
  'Sign Up': 'ثبت نام',
  'Sign Out': 'خروج',
  'Continue with': 'ادامه با',
  'Google': 'گوگل',
  'Already have an account?': 'از قبل حساب کاربری دارید؟',
  'First name': 'نام',
  'Last name': 'نام خانوادگی',
  'Username': 'نام کاربری',
  'Email': 'ایمیل',
  'Password': 'رمز عبور',
  'Confirm password': 'تایید رمز عبور',
};
