// cSpell:disable

const Map<String, String> faIR = {
  'Dakke': 'دکه',
  'Donya Ketab Hamrah': 'دنیای کتاب همراه',
  'version 1.0.0': 'نسخه ۱.۰.۰',
  'Next': 'بعدی',
  'Back': 'قبلی',
  'Skip': 'رد کردن',
  'Sign In': 'ورود',
  'Sign Out': 'خروج از حساب کاربری',
  'Password': 'رمز عبور',
  'Confirm password': 'تایید رمز عبور',
  'Save': 'ذخیره',
  'Edit': 'ویرایش',
  'Cancel': 'انصراف',
  'Ok': 'تایید',
  'Are you sure you want to sign out?':
      'آیا مطمئن هستید که می خواهید خارج شوید؟',
  'I have a voucher': 'کد تخفیف دارم',
  'Phone Number': 'شماره تلفن',
  'ex.: 9123456789': 'مثال: 9123456789',
  'Login with password': 'ورود با رمز عبور',
  'Login with phone': 'ورود با شماره تلفن',
  'Enter the code sent to the number': 'کد ارسال شده به شماره را وارد کنید',
  'Start': 'شروع',
  'Is this the correct phone number?': 'آیا این شماره صحیح است؟',
  'No': 'خیر',
  'Yes': 'بله',
  'Successful': 'موفقیت آمیز',
  'Failed': 'ناموفق',
  'Warning': 'هشدار',
  'Payment was successful': 'پرداخت موفقیت آمیز بود',
  'This Part is on Develepment': 'این بخش در حال توسعه است',
  'You have already purchased this book':
      'شما قبلاً این کتاب را خریداری کرده اید',
  'Try Again': 'تلاش مجدد',

  'My Books': 'کتاب های من',
  'Recommended': 'پیشنهاد ها',
  'Specials': 'ویژه ها',
  'More': 'بیشتر',
  'Authors': 'نویسندگان',
  'My Bookmarks': 'نشان شده های من',
  'ٔName of book, author, genre': 'نام کتاب، نویسنده، ژانر',

  'Theme': 'پوسته',
  'Dark': 'تیره',
  'Light': 'روشن',
  'Device Default': 'پیش فرض دستگاه',
  'Language': 'زبان',
  'Animation': 'انیمیشن',
  'Account Info': 'اطلاعات حساب کاربری',
  'Edit Password': 'تغییر رمز عبور',
  'Add to Cart': 'افزودن به سبد خرید',
  'Toman': 'تومان',
  'Pay': 'پرداخت',
  'Payable': 'قابل پرداخت',
  'Total': 'مجموع',
  'Discount': 'تخفیف',

  'Home': 'خانه',
  'Search': 'جستجو',
  'Library': 'کتابخانه',
  'Cart': 'سبد خرید',
  'Setting': 'تنظیمات',
  'Detail Book': 'جزئیات کتاب',

  'Free Payment': 'پرداخت رایگان',
  'Online Reading': 'خواندن آنلاین',
  'Hear Free Audio Book': 'شنیدن کتاب صوتی رایگان',
  'This is tha sample description text. ': 'این یک متن نمونه است.',

  // Errors
  'Password is required.': 'رمز عبور الزامی است.',
  'Password must contain at least 8 characters.':
      'رمز عبور باید حداقل ۸ کاراکتر باشد.',
  'Password must contain a-z, A-Z, 0-9.':
      'رمز عبور باید شامل a-z، A-Z، 0-9 باشد.',
  'Confirm Password isn\'t match.': 'تایید رمز عبور با رمز عبور مطابقت ندارد.',
  'Phone number is invalid.': 'شماره تلفن نامعتبر است.',
  'phone or password is incorrect.': 'شماره تلفن یا رمز عبور اشتباه است.',
  'Server error. Please try again later.':
      'خطای سرور. لطفا بعدا دوباره امتحان کنید.',
  'OTP code is invalid.': 'کد ارسالی نامعتبر است.',
  'This book is already in your cart.':
      'این کتاب قبلا به سبد خرید اضافه شده است.',
  'The cart is empty': 'سبد خرید خالی است',
  'You have not bookmarked a book yet.': 'شما هنوز کتابی را نشان نکرده اید.',
  'You have not purchased a book yet.': 'شما هنوز کتابی را خریداری نکرده اید.',
  'Voucher Code is invalid.': 'کد تخفیف نامعتبر است.',
  'Voucher Code is applied.': 'کد تخفیف اعمال شد.',
  'Search screen is on development.': 'صفحه جستجو در حال توسعه است.',
  'Connection failed': 'اتصال اینترنت خود را بررسی کنید',
  'No Internet Connection': 'خطا در اتصال به اینترنت',
  'Please check your internet connection and try again.':
      'لطفا اتصال اینترنت خود را بررسی کنید',
};
